### ISSUE TITLE
Flag issues by provider

### ISSUE THREAD

**Issue by neachdainn** [adeschamps/lcm-rust#17]
It would be nice if we were able to flag and filter issues by the component they were in.

**Comment by adeschamps** [comment]
Do you mean by `lcm-gen`, `lcm-derive`, and `lcm`?

**Comment by neachdainn** [comment]
I was thinking the actual provides (File, UDPM, whatever other ones we implement), but we should be able to filter by those too.

**Comment by adeschamps** [comment]
Labels exist now.
