### ISSUE TITLE
Hash is not calculated correctly

### ISSUE THREAD

**Issue by neachdainn** [adeschamps/lcm-rust#4]
Continuing conversation from #2 concerning the hash calculation.

**Comment by neachdainn** [comment]
I [previously mentioned](https://github.com/adeschamps/lcm-rust/pull/2#issuecomment-366875803) that simply including the hash wont work. After looking through the code again, I think I may be wrong since the `__lcm_hash_ptr` is not updated between fields (see code below) and LCM can't generate recursive data structures.

I think making this change should only take a few minutes, so I might be able to get it done in the next hour or so.

```cpp
uint64_t example2_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == example2_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)example2_t::getHash };

    uint64_t hash = 0x04dd33966a984612LL +
         exlcm::example_t::_computeHash(&cp) +
         exlcm::example_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}
```

**Comment by adeschamps** [comment]
lcm-gen seems perfectly happy to generate code for recursive structures (at least in C and C++), but they fail to compile (it might be possible with some hacky forward declarations).

That said, the [type specification] does contain a discussion of how recursive types are handled. I've just never seen them used in practice.

[type specification]: http://lcm-proj.github.io/type_specification.html

**Comment by neachdainn** [comment]
I suspect that recursive data structures is something that we won't be able to support even if we wanted to. I think we should pretend they aren't in the spec until someone raises an issue.
